name: Deploy on push

on:
  push:
    branches:
      - main

  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: 'placeholder-text'
      - name: Adding Known Hosts
        run: ssh-keyscan -H scuzzyfox.com >> ~/.ssh/known_hosts
      - name: Sync the remote repo
        run: ssh ubuntu@scuzzyfox.com "cd /home/ubuntu/git-repos/scuzzy-site.git && sudo git fetch origin && sudo git --work-tree=/var/www/html/scuzzy-site --git-dir=/home/ubuntu/git-repos/scuzzy-site.git checkout -f"
