name: Deploy on push

on:
  push:
    branches:
      - main

  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_KEY }}
        known_hosts: ${{ secrets.KNOWN_HOSTS }}
        if_key_exists: fail # replace / ignore / fail; optional (defaults to fail)

    - name: push to server
      run: ssh ubuntu@scuzzyfox.com "cd /user/ubuntu/git-repos/scuzzy-site.git && /usr/bin/git fetch origin"
